# Generated by Django 2.2.4 on 2021-05-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contagion_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=60)),
                ('contagion_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contagion_type.ContagionType')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
