# Generated by Django 2.2.4 on 2021-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_cases_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
