# Generated by Django 2.2.4 on 2021-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20210610_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesContagionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsts_day', models.CharField(default=None, max_length=50)),
                ('infectious_day', models.CharField(default=None, max_length=50)),
                ('symptom_day', models.CharField(default=None, max_length=50)),
                ('not_infectious_day', models.CharField(default=None, max_length=50)),
                ('free_covid', models.CharField(default=None, max_length=50)),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'vw_contagion_cases',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CasesSymptomView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.CharField(default=None, max_length=60)),
                ('contagion_day', models.CharField(default=None, max_length=60)),
                ('not_contagion_day', models.CharField(default=None, max_length=60)),
                ('not_covid', models.CharField(default=None, max_length=60)),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'vw_symptom_cases',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
