# Generated by Django 2.2.4 on 2021-05-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=60)),
                ('draggable', models.BooleanField(default=False)),
                ('fragment', models.CharField(default=None, max_length=60)),
                ('longitude', models.CharField(default=None, max_length=60)),
                ('latitude', models.CharField(default=None, max_length=60)),
                ('type_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='type_place.TypePlace')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
