# Generated by Django 2.2.4 on 2021-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_information', '0005_auto_20210601_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinformation',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
