# Generated by Django 2.2.4 on 2021-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_information', '0006_auto_20210610_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteInformationView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('first_dose_date', models.CharField(default=None, max_length=100)),
                ('second_dose_date', models.CharField(default=None, max_length=100)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField()),
                ('vaccine_name', models.CharField(default=None, max_length=100)),
                ('number_doses', models.IntegerField()),
                ('applied_doses', models.IntegerField()),
                ('name_place', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'vw_list_information',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
