# Generated by Django 2.2.4 on 2021-06-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ('id',)},
        ),
    ]
